#include<iostream.h>
#include<conio.h>
class demo
{
	int *a,i;
	public:
	void fun();

	demo()
	{
		a=new int[4];
		fun();
	}

};
void demo::fun()
{
	for(i=0;i<4;i++)
	{
		cin>>a[i];
	}
	for(i=0;i<4;i++)
	{
		cout<<endl<<a[i];
	}
}
void main()
{
	clrscr();
	demo d;
   //	d.fun();
	getch();
}
#include<conio.h>
class demo
{
	int a;
	public:
	demo()
	{
		a=o;
	}
	demo(int x)
	{
		a=x;
	}
	void fun()
	{
		cout<<endl<<"a is="<<a;
	}
};
main()
{
	clrscr();
	demo d;
	d.fun();
	d=demo(10);
	d.fun();
	getch();
	return 0;
}#include<iostream.h>
#include<conio.h>
class demo
{
	int a;
	public:
	demo()
	{
		a=o;
	}
	demo(int x)
	{
		a=x;
	}
	void fun()
	{
		cout<<endl<<"a is="<<a;
	}
};
main()
{
	clrscr();
	demo d;
	d.fun();
	d=demo(10);
	d.fun();
	getch();
	return 0;
}#include<iostream.h>
#include<conio.h>
class demo
{
	int a;
	public:
	demo()
	{
		a=o;
	}
	demo(int x)
	{
		a=x;
	}
	void fun()
	{
		cout<<endl<<"a is="<<a;
	}
};
main()
{
	clrscr();
	demo d;
	d.fun();
	d=demo(10);
	d.fun();
	getch();
	return 0;
}#include<iostream.h>
#include<conio.h>
class demo
{
	int a;
	public:
	demo()
	{
		a=o;
	}
	demo(int x)
	{
		a=x;
	}
	void fun()
	{
		cout<<endl<<"a is="<<a;
	}
};
main()
{
	clrscr();
	demo d;
	d.fun();
	d=demo(10);
	d.fun();
	getch();
	return 0;
}#include<iostream.h>
#include<conio.h>
class demo
{
	int a;
	public:
	demo()
	{
		a=o;
	}
	demo(int x)
	{
		a=x;
	}
	void fun()
	{
		cout<<endl<<"a is="<<a;
	}
};
main()
{
	clrscr();
	demo d;
	d.fun();
	d=demo(10);
	d.fun();
	getch();
	return 0;
}#include<iostream.h>
#include<conio.h>
class demo
{
	int a;
	public:
	demo()
	{
		a=o;
	}
	demo(int x)
	{
		a=x;
	}
	void fun()
	{
		cout<<endl<<"a is="<<a;
	}
};
main()
{
	clrscr();
	demo d;
	d.fun();
	d=demo(10);
	d.fun();
	getch();
	return 0;
}